import * as fs from 'fs'
import * as path from 'path'

import { getAwsDir } from './project-dir'
import { logger } from './logger'
import type { AwsCredentials, ProjectConfigResponse } from './types'

type AwsAccount = NonNullable<ProjectConfigResponse['aws']>['accounts'][number]

/**
 * Generate profile name from project code and account name.
 * Format: {projectCode}-{accountName}
 */
export function getProfileName(projectCode: string, accountName: string): string {
  return `${projectCode}-${accountName}`
}

/**
 * Generate AWS config file content in INI format.
 * Contains profile definitions with region and SSO settings (if applicable).
 */
export function generateAwsConfig(projectCode: string, accounts: AwsAccount[]): string {
  const lines: string[] = [
    `# Auto-generated by ai-support-agent for project: ${projectCode}`,
    `# Do not edit manually - this file is overwritten on config sync`,
    '',
  ]

  for (const account of accounts) {
    const profileName = getProfileName(projectCode, account.name)
    lines.push(`[profile ${profileName}]`)
    lines.push(`region = ${account.region}`)

    if (account.auth.method === 'sso') {
      lines.push(`sso_start_url = ${account.auth.startUrl}`)
      lines.push(`sso_region = ${account.auth.ssoRegion}`)
      lines.push(`sso_account_id = ${account.accountId}`)
      lines.push(`sso_role_name = ${account.auth.permissionSetName}`)
    }

    lines.push('')
  }

  return lines.join('\n')
}

/**
 * Write AWS config file to project's aws directory.
 * Uses atomic write (temp + rename) with 0o600 permissions.
 */
export function writeAwsConfig(
  projectDir: string,
  projectCode: string,
  accounts: AwsAccount[],
): void {
  try {
    const awsDir = getAwsDir(projectDir)
    if (!fs.existsSync(awsDir)) {
      fs.mkdirSync(awsDir, { recursive: true, mode: 0o700 })
    }

    const content = generateAwsConfig(projectCode, accounts)
    const configPath = path.join(awsDir, 'config')
    const tmpPath = configPath + '.tmp'
    fs.writeFileSync(tmpPath, content, { mode: 0o600 })
    fs.renameSync(tmpPath, configPath)

    logger.debug(`AWS config written to ${configPath} (${accounts.length} profiles)`)
  } catch (error) {
    logger.warn(`Failed to write AWS config: ${error}`)
  }
}

/**
 * Generate AWS credentials file content in INI format.
 */
export function generateAwsCredentials(
  projectCode: string,
  credentialMap: Map<string, AwsCredentials>,
): string {
  const lines: string[] = [
    `# Auto-generated by ai-support-agent for project: ${projectCode}`,
    `# Do not edit manually - this file is overwritten on each chat command`,
    '',
  ]

  for (const [accountName, creds] of credentialMap) {
    const profileName = getProfileName(projectCode, accountName)
    lines.push(`[${profileName}]`)
    lines.push(`aws_access_key_id = ${creds.accessKeyId}`)
    lines.push(`aws_secret_access_key = ${creds.secretAccessKey}`)
    if (creds.sessionToken) {
      lines.push(`aws_session_token = ${creds.sessionToken}`)
    }
    lines.push(`region = ${creds.region}`)
    lines.push('')
  }

  return lines.join('\n')
}

/**
 * Write AWS credentials file to project's aws directory.
 * Uses atomic write (temp + rename) with 0o600 permissions.
 */
export function writeAwsCredentials(
  projectDir: string,
  projectCode: string,
  credentialMap: Map<string, AwsCredentials>,
): void {
  try {
    const awsDir = getAwsDir(projectDir)
    if (!fs.existsSync(awsDir)) {
      fs.mkdirSync(awsDir, { recursive: true, mode: 0o700 })
    }

    const content = generateAwsCredentials(projectCode, credentialMap)
    const credentialsPath = path.join(awsDir, 'credentials')
    const tmpPath = credentialsPath + '.tmp'
    fs.writeFileSync(tmpPath, content, { mode: 0o600 })
    fs.renameSync(tmpPath, credentialsPath)

    logger.debug(`AWS credentials written to ${credentialsPath} (${credentialMap.size} profiles)`)
  } catch (error) {
    logger.warn(`Failed to write AWS credentials: ${error}`)
  }
}

/**
 * Build environment variables for Claude Code to use AWS profiles.
 * Sets AWS_CONFIG_FILE and AWS_SHARED_CREDENTIALS_FILE to project-specific paths.
 * Optionally sets AWS_PROFILE and AWS_DEFAULT_REGION for the default account.
 */
export function buildAwsProfileEnv(
  projectDir: string,
  projectCode: string,
  defaultAccountName?: string,
  defaultRegion?: string,
): Record<string, string> {
  const awsDir = getAwsDir(projectDir)
  const env: Record<string, string> = {
    AWS_CONFIG_FILE: path.join(awsDir, 'config'),
    AWS_SHARED_CREDENTIALS_FILE: path.join(awsDir, 'credentials'),
  }

  if (defaultAccountName) {
    env.AWS_PROFILE = getProfileName(projectCode, defaultAccountName)
  }

  if (defaultRegion) {
    env.AWS_DEFAULT_REGION = defaultRegion
  }

  return env
}
