import * as fs from 'fs'
import * as path from 'path'

jest.mock('fs')
jest.mock('../src/logger')
jest.mock('../src/project-dir', () => ({
  getAwsDir: (projectDir: string) =>
    path.join(projectDir, '.ai-support-agent', 'aws'),
}))

import {
  getProfileName,
  generateAwsConfig,
  writeAwsConfig,
  generateAwsCredentials,
  writeAwsCredentials,
  buildAwsProfileEnv,
} from '../src/aws-profile'
import type { AwsCredentials, ProjectConfigResponse } from '../src/types'

type AwsAccount = NonNullable<ProjectConfigResponse['aws']>['accounts'][number]

const mockedFs = fs as jest.Mocked<typeof fs>

describe('aws-profile', () => {
  beforeEach(() => {
    jest.clearAllMocks()
  })

  describe('getProfileName', () => {
    it('should return projectCode-accountName format with string', () => {
      expect(getProfileName('MBC_01', 'dev')).toBe('MBC_01-dev')
    })

    it('should handle special characters in names', () => {
      expect(getProfileName('PROJ_A', 'staging-us')).toBe('PROJ_A-staging-us')
    })

    it('should use profileName when provided in account object', () => {
      expect(getProfileName('MBC_01', { name: 'Production', profileName: 'prod' })).toBe('MBC_01-prod')
    })

    it('should fall back to name when profileName is not provided', () => {
      expect(getProfileName('MBC_01', { name: 'dev-account' })).toBe('MBC_01-dev-account')
    })

    it('should fall back to name when profileName is empty', () => {
      expect(getProfileName('MBC_01', { name: 'staging', profileName: '' })).toBe('MBC_01-staging')
    })
  })

  describe('generateAwsConfig', () => {
    it('should generate config for a single access_key account', () => {
      const accounts: AwsAccount[] = [
        {
          id: 'acc-1',
          name: 'dev',
          region: 'ap-northeast-1',
          accountId: '123456789012',
          auth: { method: 'access_key' },
          isDefault: true,
        },
      ]

      const result = generateAwsConfig('MBC_01', accounts)

      expect(result).toContain('# Auto-generated by ai-support-agent for project: MBC_01')
      expect(result).toContain('# Do not edit manually')
      expect(result).toContain('[profile MBC_01-dev]')
      expect(result).toContain('region = ap-northeast-1')
      // access_key method should not have SSO fields
      expect(result).not.toContain('sso_start_url')
      expect(result).not.toContain('sso_region')
      expect(result).not.toContain('sso_account_id')
      expect(result).not.toContain('sso_role_name')
    })

    it('should generate config for a single sso account', () => {
      const accounts: AwsAccount[] = [
        {
          id: 'acc-2',
          name: 'prod',
          region: 'us-east-1',
          accountId: '987654321098',
          auth: {
            method: 'sso',
            startUrl: 'https://my-sso.awsapps.com/start',
            ssoRegion: 'us-east-1',
            permissionSetName: 'AdministratorAccess',
          },
          isDefault: false,
        },
      ]

      const result = generateAwsConfig('PROJ_X', accounts)

      expect(result).toContain('[profile PROJ_X-prod]')
      expect(result).toContain('region = us-east-1')
      expect(result).toContain('sso_start_url = https://my-sso.awsapps.com/start')
      expect(result).toContain('sso_region = us-east-1')
      expect(result).toContain('sso_account_id = 987654321098')
      expect(result).toContain('sso_role_name = AdministratorAccess')
    })

    it('should generate config for multiple accounts', () => {
      const accounts: AwsAccount[] = [
        {
          id: 'acc-1',
          name: 'dev',
          region: 'ap-northeast-1',
          accountId: '111111111111',
          auth: { method: 'access_key' },
          isDefault: true,
        },
        {
          id: 'acc-2',
          name: 'prod',
          region: 'us-west-2',
          accountId: '222222222222',
          auth: {
            method: 'sso',
            startUrl: 'https://sso.example.com/start',
            ssoRegion: 'us-east-1',
            permissionSetName: 'ReadOnly',
          },
          isDefault: false,
        },
      ]

      const result = generateAwsConfig('MBC_01', accounts)

      expect(result).toContain('[profile MBC_01-dev]')
      expect(result).toContain('[profile MBC_01-prod]')
      expect(result).toContain('region = ap-northeast-1')
      expect(result).toContain('region = us-west-2')
    })

    it('should use profileName for profile section when available', () => {
      const accounts: AwsAccount[] = [
        {
          id: 'acc-1',
          name: 'Production Account',
          profileName: 'prod',
          region: 'ap-northeast-1',
          accountId: '123456789012',
          auth: { method: 'access_key' },
          isDefault: true,
        },
      ]

      const result = generateAwsConfig('MBC_01', accounts)

      expect(result).toContain('[profile MBC_01-prod]')
      expect(result).not.toContain('[profile MBC_01-Production Account]')
    })

    it('should include comment headers', () => {
      const result = generateAwsConfig('TEST', [])

      const lines = result.split('\n')
      expect(lines[0]).toBe('# Auto-generated by ai-support-agent for project: TEST')
      expect(lines[1]).toBe('# Do not edit manually - this file is overwritten on config sync')
    })
  })

  describe('writeAwsConfig', () => {
    const projectDir = '/tmp/test-project'
    const awsDir = path.join(projectDir, '.ai-support-agent', 'aws')
    const configPath = path.join(awsDir, 'config')
    const tmpPath = configPath + '.tmp'

    it('should create aws directory if missing and write config atomically', () => {
      mockedFs.existsSync.mockReturnValue(false)
      mockedFs.writeFileSync.mockReturnValue(undefined)
      mockedFs.renameSync.mockReturnValue(undefined)
      mockedFs.mkdirSync.mockReturnValue(undefined)

      const accounts: AwsAccount[] = [
        {
          id: 'acc-1',
          name: 'dev',
          region: 'ap-northeast-1',
          accountId: '123456789012',
          auth: { method: 'access_key' },
          isDefault: true,
        },
      ]

      writeAwsConfig(projectDir, 'MBC_01', accounts)

      expect(mockedFs.existsSync).toHaveBeenCalledWith(awsDir)
      expect(mockedFs.mkdirSync).toHaveBeenCalledWith(awsDir, { recursive: true, mode: 0o700 })
      expect(mockedFs.writeFileSync).toHaveBeenCalledWith(
        tmpPath,
        expect.stringContaining('[profile MBC_01-dev]'),
        { mode: 0o600 },
      )
      expect(mockedFs.renameSync).toHaveBeenCalledWith(tmpPath, configPath)
    })

    it('should skip mkdir if aws directory already exists', () => {
      mockedFs.existsSync.mockReturnValue(true)
      mockedFs.writeFileSync.mockReturnValue(undefined)
      mockedFs.renameSync.mockReturnValue(undefined)

      writeAwsConfig(projectDir, 'MBC_01', [])

      expect(mockedFs.mkdirSync).not.toHaveBeenCalled()
    })

    it('should handle write errors gracefully', () => {
      mockedFs.existsSync.mockReturnValue(true)
      mockedFs.writeFileSync.mockImplementation(() => {
        throw new Error('EACCES: permission denied')
      })

      // Should not throw
      expect(() => writeAwsConfig(projectDir, 'MBC_01', [])).not.toThrow()
    })
  })

  describe('generateAwsCredentials', () => {
    it('should generate credentials without sessionToken', () => {
      const credentialMap = new Map<string, AwsCredentials>([
        [
          'dev',
          {
            accessKeyId: 'AKIAIOSFODNN7EXAMPLE',
            secretAccessKey: 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY',
            region: 'ap-northeast-1',
          },
        ],
      ])

      const result = generateAwsCredentials('MBC_01', credentialMap)

      expect(result).toContain('# Auto-generated by ai-support-agent for project: MBC_01')
      expect(result).toContain('[MBC_01-dev]')
      expect(result).toContain('aws_access_key_id = AKIAIOSFODNN7EXAMPLE')
      expect(result).toContain('aws_secret_access_key = wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY')
      expect(result).toContain('region = ap-northeast-1')
      expect(result).not.toContain('aws_session_token')
    })

    it('should generate credentials with sessionToken', () => {
      const credentialMap = new Map<string, AwsCredentials>([
        [
          'staging',
          {
            accessKeyId: 'ASIASAMPLEKEY',
            secretAccessKey: 'secretSample123',
            sessionToken: 'FwoGZXIvYX...tokenValue',
            region: 'us-west-2',
          },
        ],
      ])

      const result = generateAwsCredentials('PROJ_X', credentialMap)

      expect(result).toContain('[PROJ_X-staging]')
      expect(result).toContain('aws_access_key_id = ASIASAMPLEKEY')
      expect(result).toContain('aws_secret_access_key = secretSample123')
      expect(result).toContain('aws_session_token = FwoGZXIvYX...tokenValue')
      expect(result).toContain('region = us-west-2')
    })

    it('should generate credentials for multiple accounts', () => {
      const credentialMap = new Map<string, AwsCredentials>([
        [
          'dev',
          {
            accessKeyId: 'AKIADEV',
            secretAccessKey: 'secretDev',
            region: 'ap-northeast-1',
          },
        ],
        [
          'prod',
          {
            accessKeyId: 'AKIAPROD',
            secretAccessKey: 'secretProd',
            sessionToken: 'prodToken',
            region: 'us-east-1',
          },
        ],
      ])

      const result = generateAwsCredentials('MBC_01', credentialMap)

      expect(result).toContain('[MBC_01-dev]')
      expect(result).toContain('aws_access_key_id = AKIADEV')
      expect(result).toContain('[MBC_01-prod]')
      expect(result).toContain('aws_access_key_id = AKIAPROD')
      expect(result).toContain('aws_session_token = prodToken')
    })

    it('should include comment headers', () => {
      const result = generateAwsCredentials('TEST', new Map())

      const lines = result.split('\n')
      expect(lines[0]).toBe('# Auto-generated by ai-support-agent for project: TEST')
      expect(lines[1]).toBe('# Do not edit manually - this file is overwritten on each chat command')
    })
  })

  describe('writeAwsCredentials', () => {
    const projectDir = '/tmp/test-project'
    const awsDir = path.join(projectDir, '.ai-support-agent', 'aws')
    const credentialsPath = path.join(awsDir, 'credentials')
    const tmpPath = credentialsPath + '.tmp'

    it('should create aws directory if missing and write credentials atomically', () => {
      mockedFs.existsSync.mockReturnValue(false)
      mockedFs.writeFileSync.mockReturnValue(undefined)
      mockedFs.renameSync.mockReturnValue(undefined)
      mockedFs.mkdirSync.mockReturnValue(undefined)

      const credentialMap = new Map<string, AwsCredentials>([
        [
          'dev',
          {
            accessKeyId: 'AKIATEST',
            secretAccessKey: 'secretTest',
            region: 'ap-northeast-1',
          },
        ],
      ])

      writeAwsCredentials(projectDir, 'MBC_01', credentialMap)

      expect(mockedFs.existsSync).toHaveBeenCalledWith(awsDir)
      expect(mockedFs.mkdirSync).toHaveBeenCalledWith(awsDir, { recursive: true, mode: 0o700 })
      expect(mockedFs.writeFileSync).toHaveBeenCalledWith(
        tmpPath,
        expect.stringContaining('[MBC_01-dev]'),
        { mode: 0o600 },
      )
      expect(mockedFs.renameSync).toHaveBeenCalledWith(tmpPath, credentialsPath)
    })

    it('should skip mkdir if aws directory already exists', () => {
      mockedFs.existsSync.mockReturnValue(true)
      mockedFs.writeFileSync.mockReturnValue(undefined)
      mockedFs.renameSync.mockReturnValue(undefined)

      writeAwsCredentials(projectDir, 'MBC_01', new Map())

      expect(mockedFs.mkdirSync).not.toHaveBeenCalled()
    })

    it('should handle write errors gracefully', () => {
      mockedFs.existsSync.mockReturnValue(true)
      mockedFs.writeFileSync.mockImplementation(() => {
        throw new Error('ENOSPC: no space left on device')
      })

      // Should not throw
      expect(() => writeAwsCredentials(projectDir, 'MBC_01', new Map())).not.toThrow()
    })
  })

  describe('buildAwsProfileEnv', () => {
    const projectDir = '/home/user/projects/MBC_01'
    const awsDir = path.join(projectDir, '.ai-support-agent', 'aws')

    it('should return config and credentials file paths', () => {
      const env = buildAwsProfileEnv(projectDir, 'MBC_01')

      expect(env.AWS_CONFIG_FILE).toBe(path.join(awsDir, 'config'))
      expect(env.AWS_SHARED_CREDENTIALS_FILE).toBe(path.join(awsDir, 'credentials'))
    })

    it('should set AWS_PROFILE when defaultAccountName is provided', () => {
      const env = buildAwsProfileEnv(projectDir, 'MBC_01', 'dev')

      expect(env.AWS_PROFILE).toBe('MBC_01-dev')
    })

    it('should not set AWS_PROFILE when defaultAccountName is not provided', () => {
      const env = buildAwsProfileEnv(projectDir, 'MBC_01')

      expect(env.AWS_PROFILE).toBeUndefined()
    })

    it('should not set AWS_PROFILE when defaultAccountName is undefined', () => {
      const env = buildAwsProfileEnv(projectDir, 'MBC_01', undefined)

      expect(env.AWS_PROFILE).toBeUndefined()
    })

    it('should set AWS_DEFAULT_REGION when defaultRegion is provided', () => {
      const env = buildAwsProfileEnv(projectDir, 'MBC_01', 'dev', 'ap-northeast-1')

      expect(env.AWS_DEFAULT_REGION).toBe('ap-northeast-1')
    })

    it('should not set AWS_DEFAULT_REGION when defaultRegion is not provided', () => {
      const env = buildAwsProfileEnv(projectDir, 'MBC_01', 'dev')

      expect(env.AWS_DEFAULT_REGION).toBeUndefined()
    })

    it('should set all environment variables when all parameters are provided', () => {
      const env = buildAwsProfileEnv(projectDir, 'MBC_01', 'prod', 'us-east-1')

      expect(env).toEqual({
        AWS_CONFIG_FILE: path.join(awsDir, 'config'),
        AWS_SHARED_CREDENTIALS_FILE: path.join(awsDir, 'credentials'),
        AWS_PROFILE: 'MBC_01-prod',
        AWS_DEFAULT_REGION: 'us-east-1',
      })
    })
  })
})
